#!/bin/sh
set -e

NOTIFY_ME_HOME=/var/lib/notifyme

adduser notifyme --home $NOTIFY_ME_HOME --group --system --quiet || exit 1

chown -R notifyme:notifyme /var/lib/notify-me
chmod -R 775  /var/lib/notify-me

mkdir -p /var/log/notify-me
chown -R notifyme:notifyme /var/log/notify-me
chmod -R 775  /var/log/notify-me

if [ ! -d /etc/service/notify-me ]
then
  /usr/sbin/update-service --add /etc/notify-me/sv/notify-me
else 
  sv start notify-me
fi



